server:
  port: 8080
  servlet:
    context-path: /autotest

#数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/auto_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

## mybatis 配置
mybatis:
  mapper-locations: classpath:com/yj/auto/mapper/*.xml
  type-aliases-package: com.yj.auto.entity
  configuration:
    map-underscore-to-camel-case: true



## 设置 dao 日志打印级别
logging:
  level:
    com:
      yj:
        auto:
          mapper: debug