package com.yj.auto.entity;

import java.util.Date;

public class FeatureInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.smoke
     *
     * @mbggenerated
     */
    private Integer smoke;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.scenarios_num
     *
     * @mbggenerated
     */
    private Integer scenariosNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.id
     *
     * @return the value of feature_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.id
     *
     * @param id the value for feature_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.name
     *
     * @return the value of feature_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.name
     *
     * @param name the value for feature_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.project_id
     *
     * @return the value of feature_info.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.project_id
     *
     * @param projectId the value for feature_info.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.smoke
     *
     * @return the value of feature_info.smoke
     *
     * @mbggenerated
     */
    public Integer getSmoke() {
        return smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.smoke
     *
     * @param smoke the value for feature_info.smoke
     *
     * @mbggenerated
     */
    public void setSmoke(Integer smoke) {
        this.smoke = smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.scenarios_num
     *
     * @return the value of feature_info.scenarios_num
     *
     * @mbggenerated
     */
    public Integer getScenariosNum() {
        return scenariosNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.scenarios_num
     *
     * @param scenariosNum the value for feature_info.scenarios_num
     *
     * @mbggenerated
     */
    public void setScenariosNum(Integer scenariosNum) {
        this.scenariosNum = scenariosNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.status
     *
     * @return the value of feature_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.status
     *
     * @param status the value for feature_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.operator
     *
     * @return the value of feature_info.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.operator
     *
     * @param operator the value for feature_info.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.create_time
     *
     * @return the value of feature_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.create_time
     *
     * @param createTime the value for feature_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature_info.update_time
     *
     * @return the value of feature_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature_info.update_time
     *
     * @param updateTime the value for feature_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "FeatureInfo{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", projectId=" + projectId +
                ", smoke=" + smoke +
                ", scenariosNum=" + scenariosNum +
                ", status=" + status +
                ", operator='" + operator + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}