package com.yj.auto.entity;

import java.util.Date;

public class MobileDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.os_version
     *
     * @mbggenerated
     */
    private String osVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.screen_size
     *
     * @mbggenerated
     */
    private String screenSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.client_id
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.udid
     *
     * @mbggenerated
     */
    private String udid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.slave_id
     *
     * @mbggenerated
     */
    private Integer slaveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.ready_state
     *
     * @mbggenerated
     */
    private Integer readyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.device_type
     *
     * @mbggenerated
     */
    private Integer deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.picture_url
     *
     * @mbggenerated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.last_check_time
     *
     * @mbggenerated
     */
    private Date lastCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_detail.heartbeat_last_time
     *
     * @mbggenerated
     */
    private Date heartbeatLastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.id
     *
     * @return the value of mobile_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.id
     *
     * @param id the value for mobile_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.name
     *
     * @return the value of mobile_detail.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.name
     *
     * @param name the value for mobile_detail.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.brand
     *
     * @return the value of mobile_detail.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.brand
     *
     * @param brand the value for mobile_detail.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.platform
     *
     * @return the value of mobile_detail.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.platform
     *
     * @param platform the value for mobile_detail.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.os_version
     *
     * @return the value of mobile_detail.os_version
     *
     * @mbggenerated
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.os_version
     *
     * @param osVersion the value for mobile_detail.os_version
     *
     * @mbggenerated
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.screen_size
     *
     * @return the value of mobile_detail.screen_size
     *
     * @mbggenerated
     */
    public String getScreenSize() {
        return screenSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.screen_size
     *
     * @param screenSize the value for mobile_detail.screen_size
     *
     * @mbggenerated
     */
    public void setScreenSize(String screenSize) {
        this.screenSize = screenSize == null ? null : screenSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.device_id
     *
     * @return the value of mobile_detail.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.device_id
     *
     * @param deviceId the value for mobile_detail.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.client_id
     *
     * @return the value of mobile_detail.client_id
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.client_id
     *
     * @param clientId the value for mobile_detail.client_id
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.udid
     *
     * @return the value of mobile_detail.udid
     *
     * @mbggenerated
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.udid
     *
     * @param udid the value for mobile_detail.udid
     *
     * @mbggenerated
     */
    public void setUdid(String udid) {
        this.udid = udid == null ? null : udid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.slave_id
     *
     * @return the value of mobile_detail.slave_id
     *
     * @mbggenerated
     */
    public Integer getSlaveId() {
        return slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.slave_id
     *
     * @param slaveId the value for mobile_detail.slave_id
     *
     * @mbggenerated
     */
    public void setSlaveId(Integer slaveId) {
        this.slaveId = slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.status
     *
     * @return the value of mobile_detail.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.status
     *
     * @param status the value for mobile_detail.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.ready_state
     *
     * @return the value of mobile_detail.ready_state
     *
     * @mbggenerated
     */
    public Integer getReadyState() {
        return readyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.ready_state
     *
     * @param readyState the value for mobile_detail.ready_state
     *
     * @mbggenerated
     */
    public void setReadyState(Integer readyState) {
        this.readyState = readyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.device_type
     *
     * @return the value of mobile_detail.device_type
     *
     * @mbggenerated
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.device_type
     *
     * @param deviceType the value for mobile_detail.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.password
     *
     * @return the value of mobile_detail.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.password
     *
     * @param password the value for mobile_detail.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.picture_url
     *
     * @return the value of mobile_detail.picture_url
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.picture_url
     *
     * @param pictureUrl the value for mobile_detail.picture_url
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.location
     *
     * @return the value of mobile_detail.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.location
     *
     * @param location the value for mobile_detail.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.last_check_time
     *
     * @return the value of mobile_detail.last_check_time
     *
     * @mbggenerated
     */
    public Date getLastCheckTime() {
        return lastCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.last_check_time
     *
     * @param lastCheckTime the value for mobile_detail.last_check_time
     *
     * @mbggenerated
     */
    public void setLastCheckTime(Date lastCheckTime) {
        this.lastCheckTime = lastCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_detail.heartbeat_last_time
     *
     * @return the value of mobile_detail.heartbeat_last_time
     *
     * @mbggenerated
     */
    public Date getHeartbeatLastTime() {
        return heartbeatLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_detail.heartbeat_last_time
     *
     * @param heartbeatLastTime the value for mobile_detail.heartbeat_last_time
     *
     * @mbggenerated
     */
    public void setHeartbeatLastTime(Date heartbeatLastTime) {
        this.heartbeatLastTime = heartbeatLastTime;
    }
}