package com.yj.auto.entity;

import java.util.Date;

public class TaskDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.test_package
     *
     * @mbggenerated
     */
    private String testPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.build_type
     *
     * @mbggenerated
     */
    private Integer buildType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.task_type
     *
     * @mbggenerated
     */
    private Integer taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.run_type
     *
     * @mbggenerated
     */
    private Integer runType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.job_run_type
     *
     * @mbggenerated
     */
    private Integer jobRunType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.mobile_platform
     *
     * @mbggenerated
     */
    private Integer mobilePlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.device_info
     *
     * @mbggenerated
     */
    private String deviceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.execute_time
     *
     * @mbggenerated
     */
    private String executeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.execute_end_time
     *
     * @mbggenerated
     */
    private Date executeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.case_tag
     *
     * @mbggenerated
     */
    private String caseTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.report_recipients
     *
     * @mbggenerated
     */
    private String reportRecipients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.triggerUrl
     *
     * @mbggenerated
     */
    private String triggerurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.expression
     *
     * @mbggenerated
     */
    private String expression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.id
     *
     * @return the value of task_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.id
     *
     * @param id the value for task_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.name
     *
     * @return the value of task_detail.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.name
     *
     * @param name the value for task_detail.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.test_package
     *
     * @return the value of task_detail.test_package
     *
     * @mbggenerated
     */
    public String getTestPackage() {
        return testPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.test_package
     *
     * @param testPackage the value for task_detail.test_package
     *
     * @mbggenerated
     */
    public void setTestPackage(String testPackage) {
        this.testPackage = testPackage == null ? null : testPackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.build_type
     *
     * @return the value of task_detail.build_type
     *
     * @mbggenerated
     */
    public Integer getBuildType() {
        return buildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.build_type
     *
     * @param buildType the value for task_detail.build_type
     *
     * @mbggenerated
     */
    public void setBuildType(Integer buildType) {
        this.buildType = buildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.task_type
     *
     * @return the value of task_detail.task_type
     *
     * @mbggenerated
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.task_type
     *
     * @param taskType the value for task_detail.task_type
     *
     * @mbggenerated
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.run_type
     *
     * @return the value of task_detail.run_type
     *
     * @mbggenerated
     */
    public Integer getRunType() {
        return runType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.run_type
     *
     * @param runType the value for task_detail.run_type
     *
     * @mbggenerated
     */
    public void setRunType(Integer runType) {
        this.runType = runType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.job_run_type
     *
     * @return the value of task_detail.job_run_type
     *
     * @mbggenerated
     */
    public Integer getJobRunType() {
        return jobRunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.job_run_type
     *
     * @param jobRunType the value for task_detail.job_run_type
     *
     * @mbggenerated
     */
    public void setJobRunType(Integer jobRunType) {
        this.jobRunType = jobRunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.mobile_platform
     *
     * @return the value of task_detail.mobile_platform
     *
     * @mbggenerated
     */
    public Integer getMobilePlatform() {
        return mobilePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.mobile_platform
     *
     * @param mobilePlatform the value for task_detail.mobile_platform
     *
     * @mbggenerated
     */
    public void setMobilePlatform(Integer mobilePlatform) {
        this.mobilePlatform = mobilePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.device_info
     *
     * @return the value of task_detail.device_info
     *
     * @mbggenerated
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.device_info
     *
     * @param deviceInfo the value for task_detail.device_info
     *
     * @mbggenerated
     */
    public void setDeviceInfo(String deviceInfo) {
        this.deviceInfo = deviceInfo == null ? null : deviceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.execute_time
     *
     * @return the value of task_detail.execute_time
     *
     * @mbggenerated
     */
    public String getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.execute_time
     *
     * @param executeTime the value for task_detail.execute_time
     *
     * @mbggenerated
     */
    public void setExecuteTime(String executeTime) {
        this.executeTime = executeTime == null ? null : executeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.execute_end_time
     *
     * @return the value of task_detail.execute_end_time
     *
     * @mbggenerated
     */
    public Date getExecuteEndTime() {
        return executeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.execute_end_time
     *
     * @param executeEndTime the value for task_detail.execute_end_time
     *
     * @mbggenerated
     */
    public void setExecuteEndTime(Date executeEndTime) {
        this.executeEndTime = executeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.case_tag
     *
     * @return the value of task_detail.case_tag
     *
     * @mbggenerated
     */
    public String getCaseTag() {
        return caseTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.case_tag
     *
     * @param caseTag the value for task_detail.case_tag
     *
     * @mbggenerated
     */
    public void setCaseTag(String caseTag) {
        this.caseTag = caseTag == null ? null : caseTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.report_recipients
     *
     * @return the value of task_detail.report_recipients
     *
     * @mbggenerated
     */
    public String getReportRecipients() {
        return reportRecipients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.report_recipients
     *
     * @param reportRecipients the value for task_detail.report_recipients
     *
     * @mbggenerated
     */
    public void setReportRecipients(String reportRecipients) {
        this.reportRecipients = reportRecipients == null ? null : reportRecipients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.status
     *
     * @return the value of task_detail.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.status
     *
     * @param status the value for task_detail.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.triggerUrl
     *
     * @return the value of task_detail.triggerUrl
     *
     * @mbggenerated
     */
    public String getTriggerurl() {
        return triggerurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.triggerUrl
     *
     * @param triggerurl the value for task_detail.triggerUrl
     *
     * @mbggenerated
     */
    public void setTriggerurl(String triggerurl) {
        this.triggerurl = triggerurl == null ? null : triggerurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.expression
     *
     * @return the value of task_detail.expression
     *
     * @mbggenerated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.expression
     *
     * @param expression the value for task_detail.expression
     *
     * @mbggenerated
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.operator
     *
     * @return the value of task_detail.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.operator
     *
     * @param operator the value for task_detail.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.create_time
     *
     * @return the value of task_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.create_time
     *
     * @param createTime the value for task_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.update_time
     *
     * @return the value of task_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.update_time
     *
     * @param updateTime the value for task_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}