package com.yj.auto.entity;

import java.util.Date;

public class TaskReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.trigger_id
     *
     * @mbggenerated
     */
    private Integer triggerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.test_package
     *
     * @mbggenerated
     */
    private String testPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.features_num
     *
     * @mbggenerated
     */
    private Integer featuresNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.feature_fassed_num
     *
     * @mbggenerated
     */
    private Integer featureFassedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.feature_failed_num
     *
     * @mbggenerated
     */
    private Integer featureFailedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.scenarios_num
     *
     * @mbggenerated
     */
    private Integer scenariosNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.scenario_passed_num
     *
     * @mbggenerated
     */
    private Integer scenarioPassedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.scenario_failed_num
     *
     * @mbggenerated
     */
    private Integer scenarioFailedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.steps_num
     *
     * @mbggenerated
     */
    private Integer stepsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.step_passed_num
     *
     * @mbggenerated
     */
    private Integer stepPassedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.step_skipped_num
     *
     * @mbggenerated
     */
    private Integer stepSkippedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.step_failed_num
     *
     * @mbggenerated
     */
    private Integer stepFailedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.case_pass_rate
     *
     * @mbggenerated
     */
    private String casePassRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.feature_pass_rate
     *
     * @mbggenerated
     */
    private String featurePassRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.elapsed_time
     *
     * @mbggenerated
     */
    private String elapsedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.execute_time
     *
     * @mbggenerated
     */
    private Date executeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.execute_end_time
     *
     * @mbggenerated
     */
    private Date executeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_report.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.id
     *
     * @return the value of task_report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.id
     *
     * @param id the value for task_report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.task_id
     *
     * @return the value of task_report.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.task_id
     *
     * @param taskId the value for task_report.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.trigger_id
     *
     * @return the value of task_report.trigger_id
     *
     * @mbggenerated
     */
    public Integer getTriggerId() {
        return triggerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.trigger_id
     *
     * @param triggerId the value for task_report.trigger_id
     *
     * @mbggenerated
     */
    public void setTriggerId(Integer triggerId) {
        this.triggerId = triggerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.test_package
     *
     * @return the value of task_report.test_package
     *
     * @mbggenerated
     */
    public String getTestPackage() {
        return testPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.test_package
     *
     * @param testPackage the value for task_report.test_package
     *
     * @mbggenerated
     */
    public void setTestPackage(String testPackage) {
        this.testPackage = testPackage == null ? null : testPackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.features_num
     *
     * @return the value of task_report.features_num
     *
     * @mbggenerated
     */
    public Integer getFeaturesNum() {
        return featuresNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.features_num
     *
     * @param featuresNum the value for task_report.features_num
     *
     * @mbggenerated
     */
    public void setFeaturesNum(Integer featuresNum) {
        this.featuresNum = featuresNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.feature_fassed_num
     *
     * @return the value of task_report.feature_fassed_num
     *
     * @mbggenerated
     */
    public Integer getFeatureFassedNum() {
        return featureFassedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.feature_fassed_num
     *
     * @param featureFassedNum the value for task_report.feature_fassed_num
     *
     * @mbggenerated
     */
    public void setFeatureFassedNum(Integer featureFassedNum) {
        this.featureFassedNum = featureFassedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.feature_failed_num
     *
     * @return the value of task_report.feature_failed_num
     *
     * @mbggenerated
     */
    public Integer getFeatureFailedNum() {
        return featureFailedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.feature_failed_num
     *
     * @param featureFailedNum the value for task_report.feature_failed_num
     *
     * @mbggenerated
     */
    public void setFeatureFailedNum(Integer featureFailedNum) {
        this.featureFailedNum = featureFailedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.scenarios_num
     *
     * @return the value of task_report.scenarios_num
     *
     * @mbggenerated
     */
    public Integer getScenariosNum() {
        return scenariosNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.scenarios_num
     *
     * @param scenariosNum the value for task_report.scenarios_num
     *
     * @mbggenerated
     */
    public void setScenariosNum(Integer scenariosNum) {
        this.scenariosNum = scenariosNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.scenario_passed_num
     *
     * @return the value of task_report.scenario_passed_num
     *
     * @mbggenerated
     */
    public Integer getScenarioPassedNum() {
        return scenarioPassedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.scenario_passed_num
     *
     * @param scenarioPassedNum the value for task_report.scenario_passed_num
     *
     * @mbggenerated
     */
    public void setScenarioPassedNum(Integer scenarioPassedNum) {
        this.scenarioPassedNum = scenarioPassedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.scenario_failed_num
     *
     * @return the value of task_report.scenario_failed_num
     *
     * @mbggenerated
     */
    public Integer getScenarioFailedNum() {
        return scenarioFailedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.scenario_failed_num
     *
     * @param scenarioFailedNum the value for task_report.scenario_failed_num
     *
     * @mbggenerated
     */
    public void setScenarioFailedNum(Integer scenarioFailedNum) {
        this.scenarioFailedNum = scenarioFailedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.steps_num
     *
     * @return the value of task_report.steps_num
     *
     * @mbggenerated
     */
    public Integer getStepsNum() {
        return stepsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.steps_num
     *
     * @param stepsNum the value for task_report.steps_num
     *
     * @mbggenerated
     */
    public void setStepsNum(Integer stepsNum) {
        this.stepsNum = stepsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.step_passed_num
     *
     * @return the value of task_report.step_passed_num
     *
     * @mbggenerated
     */
    public Integer getStepPassedNum() {
        return stepPassedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.step_passed_num
     *
     * @param stepPassedNum the value for task_report.step_passed_num
     *
     * @mbggenerated
     */
    public void setStepPassedNum(Integer stepPassedNum) {
        this.stepPassedNum = stepPassedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.step_skipped_num
     *
     * @return the value of task_report.step_skipped_num
     *
     * @mbggenerated
     */
    public Integer getStepSkippedNum() {
        return stepSkippedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.step_skipped_num
     *
     * @param stepSkippedNum the value for task_report.step_skipped_num
     *
     * @mbggenerated
     */
    public void setStepSkippedNum(Integer stepSkippedNum) {
        this.stepSkippedNum = stepSkippedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.step_failed_num
     *
     * @return the value of task_report.step_failed_num
     *
     * @mbggenerated
     */
    public Integer getStepFailedNum() {
        return stepFailedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.step_failed_num
     *
     * @param stepFailedNum the value for task_report.step_failed_num
     *
     * @mbggenerated
     */
    public void setStepFailedNum(Integer stepFailedNum) {
        this.stepFailedNum = stepFailedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.case_pass_rate
     *
     * @return the value of task_report.case_pass_rate
     *
     * @mbggenerated
     */
    public String getCasePassRate() {
        return casePassRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.case_pass_rate
     *
     * @param casePassRate the value for task_report.case_pass_rate
     *
     * @mbggenerated
     */
    public void setCasePassRate(String casePassRate) {
        this.casePassRate = casePassRate == null ? null : casePassRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.feature_pass_rate
     *
     * @return the value of task_report.feature_pass_rate
     *
     * @mbggenerated
     */
    public String getFeaturePassRate() {
        return featurePassRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.feature_pass_rate
     *
     * @param featurePassRate the value for task_report.feature_pass_rate
     *
     * @mbggenerated
     */
    public void setFeaturePassRate(String featurePassRate) {
        this.featurePassRate = featurePassRate == null ? null : featurePassRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.operator
     *
     * @return the value of task_report.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.operator
     *
     * @param operator the value for task_report.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.elapsed_time
     *
     * @return the value of task_report.elapsed_time
     *
     * @mbggenerated
     */
    public String getElapsedTime() {
        return elapsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.elapsed_time
     *
     * @param elapsedTime the value for task_report.elapsed_time
     *
     * @mbggenerated
     */
    public void setElapsedTime(String elapsedTime) {
        this.elapsedTime = elapsedTime == null ? null : elapsedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.execute_time
     *
     * @return the value of task_report.execute_time
     *
     * @mbggenerated
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.execute_time
     *
     * @param executeTime the value for task_report.execute_time
     *
     * @mbggenerated
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.execute_end_time
     *
     * @return the value of task_report.execute_end_time
     *
     * @mbggenerated
     */
    public Date getExecuteEndTime() {
        return executeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.execute_end_time
     *
     * @param executeEndTime the value for task_report.execute_end_time
     *
     * @mbggenerated
     */
    public void setExecuteEndTime(Date executeEndTime) {
        this.executeEndTime = executeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.createTime
     *
     * @return the value of task_report.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.createTime
     *
     * @param createtime the value for task_report.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.updateTime
     *
     * @return the value of task_report.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.updateTime
     *
     * @param updatetime the value for task_report.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_report.status
     *
     * @return the value of task_report.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_report.status
     *
     * @param status the value for task_report.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}