package com.yj.auto.mapper;

import com.yj.auto.entity.FeatureInfo;

public interface FeatureInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int insert(FeatureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int insertSelective(FeatureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    FeatureInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FeatureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FeatureInfo record);
}