package com.yj.auto.mapper;

import com.yj.auto.entity.FeatureInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FeatureInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int insert(FeatureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int insertSelective(FeatureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    FeatureInfo selectByPrimaryKey(Integer id);

    FeatureInfo selectByNameAndProjectId(@Param("name") String name, @Param("projectId") Integer projectId);

    List<FeatureInfo> selectByNamesAndProjectId(@Param("names") List<String> name, @Param("projectId") Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FeatureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FeatureInfo record);

    int deleteByIds(@Param("Ids") List<Integer> ids);
}