package com.yj.auto.mapper;

import com.yj.auto.entity.MobileDetail;

public interface MobileDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_detail
     *
     * @mbggenerated
     */
    int insert(MobileDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_detail
     *
     * @mbggenerated
     */
    int insertSelective(MobileDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_detail
     *
     * @mbggenerated
     */
    MobileDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MobileDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MobileDetail record);
}