package com.yj.auto.mapper;

import com.yj.auto.entity.SlaveInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SlaveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_info
     *
     * @mbggenerated
     */
    int insert(SlaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_info
     *
     * @mbggenerated
     */
    int insertSelective(SlaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_info
     *
     * @mbggenerated
     */
    SlaveInfo selectByPrimaryKey(Long id);

    List<SlaveInfo> selective(@Param("record") SlaveInfo record, @Param("limit") Integer limit, @Param("offset") Integer offset);

    Long getSalveCount(@Param("record") SlaveInfo record);

    List<SlaveInfo> selectAll(@Param("limit") Integer limit, @Param("offset") Integer offset);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SlaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SlaveInfo record);
}