package com.yj.auto.mapper;

import com.yj.auto.entity.TaskDetail;

public interface TaskDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int insert(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int insertSelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    TaskDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskDetail record);
}