package com.yj.auto.mapper;

import com.yj.auto.entity.TaskRunInfo;

public interface TaskRunInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_run_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_run_info
     *
     * @mbggenerated
     */
    int insert(TaskRunInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_run_info
     *
     * @mbggenerated
     */
    int insertSelective(TaskRunInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_run_info
     *
     * @mbggenerated
     */
    TaskRunInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_run_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskRunInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_run_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskRunInfo record);
}